# Generated by Django 6.0.2 on 2026-05-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_view_count_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('wallet', 'Hamyon orqali'), ('cash', "Naqd pul (Kuryer qo'lida)")], default='cash', max_length=20),
        ),
    ]
